CREATE DATABASE C4_BTTH_Bai2
USE C4_BTTH_Bai2
-- Tạo bảng Khoa
CREATE TABLE KHOA (
    Makhoa NVARCHAR(10) PRIMARY KEY,
    Tenkhoa NVARCHAR(30)
);

-- Tạo bảng Lop
CREATE TABLE LOP (
    Malop NVARCHAR(10) PRIMARY KEY,
    Tenlop NVARCHAR(30),
    Makhoa NVARCHAR(10) REFERENCES KHOA(Makhoa)
);

-- Tạo bảng SinhVien
CREATE TABLE SINHVIEN (
    MaSV NVARCHAR(10) PRIMARY KEY,
    Hoten NVARCHAR(50),
    Ngaysinh DATE,
    Diachi NVARCHAR(100),
    Gioitinh NVARCHAR(5),
    Malop NVARCHAR(10) REFERENCES LOP(Malop)
);

-- Tạo bảng Monhoc
CREATE TABLE MONHOC (
    MaMH NVARCHAR(10) PRIMARY KEY,
    TenMH NVARCHAR(50),
    SoTC INT
);

-- Tạo bảng Ketqua
CREATE TABLE KETQUA (
    MaSV NVARCHAR(10) REFERENCES SINHVIEN(MaSV),
    MaMH NVARCHAR(10) REFERENCES MONHOC(MaMH),
    Diem FLOAT,
    PRIMARY KEY (MaSV, MaMH)
);

-- Tạo các nhóm quyền
CREATE ROLE Bangiamhieu;
CREATE ROLE Daotao;
CREATE ROLE Khoa;
CREATE ROLE Sinhvien;

-- Gán quyền cho các nhóm quyền
GRANT INSERT, UPDATE, DELETE ON KHOA TO Bangiamhieu;
GRANT INSERT, UPDATE, DELETE ON LOP TO DaoTao;
GRANT INSERT, UPDATE, DELETE ON SINHVIEN TO DaoTao;
GRANT INSERT, UPDATE, DELETE ON KETQUA TO DaoTao;
GRANT INSERT, UPDATE, DELETE ON MONHOC TO Khoa;
GRANT SELECT ON SINHVIEN TO Sinhvien;
GRANT SELECT ON KETQUA TO Sinhvien;


-- Tạo các tài khoản đăng nhập
CREATE LOGIN Ngoan WITH PASSWORD = 'abcxyz';
CREATE LOGIN Thanh WITH PASSWORD = 'abcxyz';
CREATE LOGIN Nguyen WITH PASSWORD = 'abcxyz';
CREATE LOGIN Phuong WITH PASSWORD = 'abcxyz';
CREATE LOGIN Anh WITH PASSWORD = 'abcxyz';
CREATE LOGIN Hoa WITH PASSWORD = 'abcxyz';
CREATE LOGIN Hong WITH PASSWORD = 'abcxyz';

-- Tạo các tài khoản người dùng và gán vào nhóm quyền tương ứng
CREATE USER Ngoan FOR LOGIN Ngoan WITH DEFAULT_SCHEMA = dbo;
CREATE USER Thanh FOR LOGIN Thanh WITH DEFAULT_SCHEMA = dbo;
CREATE USER Nguyen FOR LOGIN Nguyen WITH DEFAULT_SCHEMA = dbo;
CREATE USER Phuong FOR LOGIN Phuong WITH DEFAULT_SCHEMA = dbo;
CREATE USER Anh FOR LOGIN Anh WITH DEFAULT_SCHEMA = dbo;
CREATE USER Hoa FOR LOGIN Hoa WITH DEFAULT_SCHEMA = dbo;
CREATE USER Hong FOR LOGIN Hong WITH DEFAULT_SCHEMA = dbo;

-- Gán vào nhóm quyền cho từng thành viên
ALTER ROLE Bangiamhieu ADD MEMBER Ngoan;
ALTER ROLE Daotao ADD MEMBER Thanh;
ALTER ROLE Daotao ADD MEMBER Nguyen;
ALTER ROLE Khoa ADD MEMBER Phuong;
ALTER ROLE Khoa ADD MEMBER Anh;
ALTER ROLE Sinhvien ADD MEMBER Hong;
ALTER ROLE Sinhvien ADD MEMBER Hoa;


