USE Buoi2_BTLT_QLDoAn1

CREATE TABLE LOAIDETAI_CHUYENDL (
    MALOAI VARCHAR(10) CONSTRAINT PK_LOAIDETAI_CHUYENDL PRIMARY KEY,
    TENLOAI NVARCHAR(50)
);


CREATE TABLE DETAI_CHUYENDL (
    MADT VARCHAR(10) CONSTRAINT PK_DETAI_CHUYENDL PRIMARY KEY,
    TENDT NVARCHAR(50),
    SOSV_TOIDA INT,
    SOSV_DANGKY INT,
    MALOAI VARCHAR(10),
    CONSTRAINT FK_LOAIDETAI_CHUYENDL FOREIGN KEY (MALOAI) REFERENCES LOAIDETAI_CHUYENDL(MALOAI)
);

CREATE TABLE LOP_CHUYENDL (
    MALOP VARCHAR(10) CONSTRAINT PK_LOP_CHUYENDL PRIMARY KEY,
    TENLOP NVARCHAR(50),
	SISO INT,
    SOSV_DOAN INT,
    SOSV_KHOALUAN INT
);

CREATE TABLE SINHVIEN_CHUYENDL (
    MASV VARCHAR(10) CONSTRAINT PK_SINHVIEN_CHUYENDL PRIMARY KEY,
    HOTENSV NVARCHAR(50),
    NGAYSINH DATE,
    PHAI BIT,
    MALOP VARCHAR(10),
    DIEMTB FLOAT,
    DIENLAMDETAI NVARCHAR(50),
    MADT VARCHAR(10),
    CONSTRAINT FK_LOP_CHUYENDL FOREIGN KEY (MALOP) REFERENCES LOP_CHUYENDL(MALOP),
    CONSTRAINT FK_DETAI_CHUYENDL FOREIGN KEY (MADT) REFERENCES DETAI_CHUYENDL(MADT)
);

SELECT * FROM SINHVIEN_CHUYENDL

-- Chuyển dữ liệu từ bảng DETAI sang file txt
EXEC xp_cmdshell 'bcp "SELECT * FROM Buoi2_BTLT_QLDoAn1.dbo.DETAI" queryout "D:\DATABASE\BUOI2\QL_DA.txt" -c -T -S ZOHANUBIS'

-- Chuyển dữ liệu từ file txt vào bảng DETAI_CHUYENDL
EXEC xp_cmdshell 'bcp Buoi2_BTLT_QLDoAn1.dbo.DETAI_CHUYENDL in "D:\DATABASE\BUOI2\DeTai_ChuyenDL.txt" -c -T -S ZOHANUBIS'

-- Chuyển dữ liệu từ bảng SINHVIEN sang file csv
EXEC xp_cmdshell 'bcp "SELECT MASV, HOTENSV, DIENLAMDETAI, MADT FROM Buoi2_BTLT_QLDoAn1.dbo.SINHVIEN" queryout "D:\DATABASE\BUOI2\SinhVien.txt" -c -T -S ZOHANUBIS'

-- Tạo bảng ảo (View)
CREATE VIEW VIEW_DETAI AS
SELECT DETAI_CHUYENDL.MADT, DETAI_CHUYENDL.TENDT, LOAIDETAI_CHUYENDL.TENLOAI
FROM DETAI_CHUYENDL
JOIN LOAIDETAI_CHUYENDL ON DETAI_CHUYENDL.MALOAI = LOAIDETAI_CHUYENDL.MALOAI;


EXEC xp_cmdshell 'bcp "SELECT * FROM VIEW_DETAI" queryout "D:\DATABASE\BUOI2\BangAo.txt" -c -T -S ZOHANUBIS'
