CREATE DATABASE Bai1_BTVN2
GO

USE Bai1_BTVN2
GO

CREATE TABLE TACGIA(
	MATG VARCHAR(10) PRIMARY KEY,
	TENTG NVARCHAR(100),
	DIACHI NVARCHAR (100)
);

CREATE TABLE LOAISACH(
	MALOAI VARCHAR(10) PRIMARY KEY,
	TENLOAI NVARCHAR(100)
);

CREATE TABLE NHAXUATBAN(
	MANXB VARCHAR(10) PRIMARY KEY,
	TENNXB NVARCHAR(100),
	DCNXB NVARCHAR(100),
	DTNXB VARCHAR(15)
);
CREATE TABLE SACH(
	MASH VARCHAR(10) PRIMARY KEY,
	TENSH NVARCHAR(100),
	MATG VARCHAR(10),
	NAMXB VARCHAR(10),
	MANXB VARCHAR(10),
	MALOAI VARCHAR(10),
	CONSTRAINT FK_SACH_TACGIA FOREIGN KEY (MATG) REFERENCES TACGIA (MATG),
	CONSTRAINT FK_SACH_NHAXUATBAN FOREIGN KEY (MANXB) REFERENCES NHAXUATBAN (MANXB),
	CONSTRAINT FK_SACH_LOAISACH FOREIGN KEY (MALOAI) REFERENCES LOAISACH (MALOAI)
);

CREATE TABLE DOCGIA(
	MADG VARCHAR(10) PRIMARY KEY,
	TENDG NVARCHAR(100), 
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	LIENHE VARCHAR(15),
);
SET DATEFORMAT DMY

CREATE TABLE MUONTRASACH(
	MADG VARCHAR(10),
	MASH VARCHAR(10),
	CONSTRAINT FK_MUONTRASACH_DOCGIA FOREIGN KEY (MADG) REFERENCES DOCGIA (MADG),
	CONSTRAINT FK_MUONTRASACH_SACH FOREIGN KEY (MASH) REFERENCES SACH (MASH),
	NGAYMUON DATE,
	NGAYTRA DATE
);

INSERT INTO TACGIA (MATG, TENTG, DIACHI)
VALUES
  ('TG001', N'Nguyễn Hữu Anh', N'Q3, TP. HCM'),
  ('TG002', N'Tô Hoài', N'Bình Thạnh, TP. HCM'),
  ('TG003', N'Nguyễn Quang Sang', N'Trảng Bàng, Tây Ninh'),
  ('TG004', N'Hồ Tùng Mậu', N'Trảng Bom, Đồng Nai'),
  ('TG005', N'Thi Anh Trung', N'Bến Lức, Long An'),
  ('TG006', N'Nguyễn Nhật Ánh', N'Q1, TP. HCM');

 INSERT INTO LOAISACH (MALOAI, TENLOAI)
VALUES
  ('SH', N'SÁCH'),
  ('TR', N'TRUYỆN'),
  ('TC', N'TẠP CHÍ');

INSERT INTO NHAXUATBAN (MANXB, TENNXB, DCNXB, DTNXB)
VALUES
  ('NXB01', N'Đại học quốc gia TP.HCM', N'Quận 1, TP. HCM', '08.765348758'),
  ('NXB02', N'Đại học quốc gia Hà Nội', N'Quận Cầu Giấy, Hà Nội', '04.765476574'),
  ('NXB03', N'Thanh Niên', N'Quận 3, TP. HCM', '08.76547566546'),
  ('NXB04', N'Tổng Hợp', N'Quận Thanh Xuân, Hà Nội', '04.876847676'),
  ('NXB05', N'Nhi Đồng', N'Quận 10, TP. HCM', '08.765746767');

INSERT INTO SACH (MASH, TENSH, MATG, NAMXB, MANXB, MALOAI)
VALUES
  ('SH001', N'Toán rời rạc', (SELECT MATG FROM TACGIA WHERE MATG = 'TG001'), 1998, (SELECT MANXB FROM NHAXUATBAN WHERE MANXB = 'NXB01'), (SELECT MALOAI FROM LOAISACH WHERE MALOAI = 'SH')),
  ('TR001', N'Dế mèn phiêu lưu ký', (SELECT MATG FROM TACGIA WHERE MATG = 'TG002'), 1997, (SELECT MANXB FROM NHAXUATBAN WHERE MANXB = 'NXB05'), (SELECT MALOAI FROM LOAISACH WHERE MALOAI = 'TR')),
  ('TR002', N'Bàn có 5 chỗ ngồi', (SELECT MATG FROM TACGIA WHERE MATG = 'TG006'), 2000, (SELECT MANXB FROM NHAXUATBAN WHERE MANXB = 'NXB05'), (SELECT MALOAI FROM LOAISACH WHERE MALOAI = 'TR')),
  ('TC001', N'Tạp chí Tin học và Điều khiển số 6/2015', (SELECT MATG FROM TACGIA WHERE MATG = 'TG003'), 2015, (SELECT MANXB FROM NHAXUATBAN WHERE MANXB = 'NXB04'), (SELECT MALOAI FROM LOAISACH WHERE MALOAI = 'TC')),
  ('TC002', N'Tạp chí Tin học và Điều khiển số 9/2015', (SELECT MATG FROM TACGIA WHERE MATG = 'TG003'), 2015, (SELECT MANXB FROM NHAXUATBAN WHERE MANXB = 'NXB04'), (SELECT MALOAI FROM LOAISACH WHERE MALOAI = 'TC')),
  ('SH002', N'Kỹ thuật lập trình C#', (SELECT MATG FROM TACGIA WHERE MATG = 'TG004'), 1998, (SELECT MANXB FROM NHAXUATBAN WHERE MANXB = 'NXB04'), (SELECT MALOAI FROM LOAISACH WHERE MALOAI = 'SH'));

INSERT INTO DOCGIA (MADG, TENDG, NGAYSINH, GIOITINH, LIENHE)
VALUES 
('DG001', N'Nguyễn Thanh Nam', '1990-09-13', N'Nam', '01681234567'),
('DG002', N'Lê Văn Anh', '1994-04-24', N'Nam', '0982999011'),
('DG003', N'Trần Thanh Bình', '1989-10-30', N'Nữ', '01659000123'),
('DG004', N'Nguyễn Thị Thanh', '1997-02-02', N'Nữ', '01231452370');

INSERT INTO MUONTRASACH (MADG, MASH, NGAYMUON, NGAYTRA)
VALUES 
('DG004', 'SH002', '2016-05-21', '2016-05-28'),
('DG001', 'SH001', '2016-06-01', '2016-06-02'),
('DG003', 'TC001', '2016-06-01', '2016-06-11'),
('DG001', 'SH002', '2016-06-01', NULL);

--1. Cho biết thông tin những cuốn sách thuộc nhà xuất bản Đại học quốc gia TP.HCM.
SELECT MASH, TENSH, TENNXB, NAMXB FROM SACH
JOIN NHAXUATBAN ON SACH.MANXB = NHAXUATBAN.MANXB
WHERE TENNXB =  N'Đại học quốc gia TP.HCM';
--2. Độc giả Nguyễn Thanh Nam đã mượn bao nhiêu cuốn sách trong ngày 01/06/2016?
SELECT COUNT(*) AS SoLuongSachMuon
FROM MUONTRASACH
JOIN DOCGIA ON MUONTRASACH.MADG = DOCGIA.MADG
WHERE DOCGIA.TENDG = N'Nguyễn Thanh Nam' AND NGAYMUON = '2016-06-01';
--3. Những cuốn sách nào của tác giả Nguyễn Hữu Anh?
SELECT TENSH 
FROM SACH 
INNER JOIN TACGIA ON SACH.MATG = TACGIA.MATG 
WHERE TACGIA.TENTG LIKE N'%Nguyễn Hữu Anh%'
--4. Mỗi loại sách có bao nhiêu cuốn sách?
SELECT LOAISACH.TENLOAI, COUNT(*) AS SOLUONG 
FROM SACH 
INNER JOIN LOAISACH ON SACH.MALOAI = LOAISACH.MALOAI 
GROUP BY LOAISACH.TENLOAI
--5. Cho biết mã và tên của những độc giả mượn nhiều sách nhất.
SELECT TOP 1 DOCGIA.MADG, DOCGIA.TENDG, COUNT(*) AS SOLUONG 
FROM MUONTRASACH 
INNER JOIN DOCGIA ON MUONTRASACH.MADG = DOCGIA.MADG 
GROUP BY DOCGIA.MADG, DOCGIA.TENDG 
ORDER BY COUNT(*) DESC
--6. Cho biết tên những cuốn sách chưa được mượn lần nào.
SELECT TENSH
FROM SACH
WHERE MASH NOT IN (
	SELECT MASH
	FROM MUONTRASACH
)
--7. Những độc giả nào (MADG, TENDG) mượn 3 cuốn sách?
SELECT DOCGIA.MADG, DOCGIA.TENDG
FROM DOCGIA
INNER JOIN MUONTRASACH ON DOCGIA.MADG = MUONTRASACH.MADG
GROUP BY DOCGIA.MADG, DOCGIA.TENDG
HAVING COUNT(*) = 3


