CREATE DATABASE QUANLY_SINHVIEN
USE QUANLY_SINHVIEN

CREATE TABLE KHOA (
    MAKHOA VARCHAR(50) PRIMARY KEY,
    TENKHOA NVARCHAR(50)
);

CREATE TABLE LOP (
    MALOP VARCHAR(50) PRIMARY KEY,
    TENLOP NVARCHAR(50),
    SISODK INT,
    MAKHOA VARCHAR(50),
    CONSTRAINT FK_LOP_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE SINHVIEN (
    MASV VARCHAR(50) PRIMARY KEY,
    HOTEN NVARCHAR(50),
    NGSINH DATE,
    DCHI NVARCHAR(50),
    GIOITINH VARCHAR(10),
    MALOP VARCHAR(50),
    CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);

CREATE TABLE MONHOC (
    MAMH VARCHAR(50) PRIMARY KEY,
    TENMH NVARCHAR(50),
    SOTIET INT
);

CREATE TABLE KETQUA (
    MASV VARCHAR(50),
    MAMH VARCHAR(50),
    DIEM FLOAT,
    CONSTRAINT PK_KETQUA PRIMARY KEY (MASV, MAMH),
    CONSTRAINT FK_KETQUA_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_KETQUA_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);
