CREATE DATABASE QL_DIACHIDO
GO

USE QL_DIACHIDO 

CREATE TABLE KHOA(
    MAKHOA VARCHAR(10) NOT NULL,
    TENKHOA NVARCHAR(50),
    DIADIEM NVARCHAR(50),
    CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
);
CREATE TABLE SINHVIEN(
    MASV VARCHAR(10) NOT NULL,
    HOTEN NVARCHAR(50),
    NGAYSINHD DATE,
    PHAI NVARCHAR(10),
    MAKHOA VARCHAR(10) NOT NULL,
    CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV),
    CONSTRAINT FK_SINHVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA) 
);
CREATE TABLE DIACHIDO(
    MADCD VARCHAR(10) NOT NULL,
    TENDCD NVARCHAR(50),
    NGAYDI DATE,
    CONSTRAINT PK_DIACHIDO PRIMARY KEY (MADCD)
);
CREATE TABLE DANGKY(
    MASV VARCHAR(10) NOT NULL,
    MADCD VARCHAR(10) NOT NULL,
    NGAYDK DATE, 
    CONSTRAINT PK_DANGKY PRIMARY KEY (MASV,MADCD),
    CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    CONSTRAINT FK_DANGKY_DIACHIDO FOREIGN KEY (MADCD) REFERENCES DIACHIDO(MADCD)
);
-------------------------RÀNG BUỘC TOÀN VẸN----------------------------
--a) -- Ràng buộc mặc định cho cột DIADIEM trong bảng KHOA
ALTER TABLE KHOA
ADD CONSTRAINT DF_DIADIEM DEFAULT N'Chưa xác định' FOR DIADIEM;
--b) -- Ràng buộc duy nhất cho cột TENKHOA trong bảng KHOA
ALTER TABLE KHOA
ADD CONSTRAINT UQ_TENKHOA UNIQUE (TENKHOA);

-- Ràng buộc duy nhất cho cột TENDCD trong bảng DIACHIDO
ALTER TABLE DIACHIDO
ADD CONSTRAINT UQ_TENDCD UNIQUE (TENDCD);
--c) -- Tạo trigger
CREATE TRIGGER TRG_KIEMTRA_NGAYDI
ON DIACHIDO
AFTER INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM inserted WHERE NGAYDI <= GETDATE())
    BEGIN
        RAISERROR ('Ngày đi phải lớn hơn ngày hiện tại!', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
---- Tạo trigger
CREATE TRIGGER TRG_KIEMTRA_PHAI
ON SINHVIEN
AFTER INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM inserted WHERE PHAI NOT IN (N'Nam', N'Nữ'))
    BEGIN
        RAISERROR ('Phái chỉ được là "Nam" hoặc "Nữ"!', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
---------------------------------TRUY VẤN-----------------------------
--a. Tên địa chỉ đỏ và ngày đi địa chỉ đỏ của sinh viên có mã số (SV001) đăng ký tham gia địa chỉ đỏ:
SELECT D.TENDCD, D.NGAYDI
FROM DANGKY DK
JOIN DIACHIDO D ON DK.MADCD = D.MADCD
WHERE DK.MASV = 'SV001';
--b. Thông tin địa chỉ đỏ mà không có sinh viên nào đăng ký (MADCD, TENDCD
SELECT MADCD, TENDCD
FROM DIACHIDO
WHERE MADCD NOT IN (SELECT MADCD FROM DANGKY);
--c) Danh sách khoa (TENKH) và số lượng sinh viên có đăng ký tham gia địa chỉ đỏ
SELECT K.TENKHOA, COUNT(DISTINCT DK.MASV) AS SoLuongSinhVien
FROM DANGKY DK
JOIN SINHVIEN SV ON DK.MASV = SV.MASV
JOIN KHOA K ON SV.MAKHOA = K.MAKHOA
GROUP BY K.TENKHOA;
--d.Thông tin khoa (MAKHOA, TENKHOA) có số lượng sinh viên đăng ký tham gia địa chỉ đỏ nhiều nhất
SELECT TOP 1 K.MAKHOA, K.TENKHOA
FROM KHOA K
JOIN SINHVIEN SV ON K.MAKHOA = SV.MAKHOA
JOIN DANGKY DK ON SV.MASV = DK.MASV
GROUP BY K.MAKHOA, K.TENKHOA
ORDER BY COUNT(DISTINCT SV.MASV) DESC;

------------------------------------------------------
INSERT INTO KHOA (MAKHOA, TENKHOA, DIADIEM)
VALUES ('K001', N'Khoa Kỹ thuật', N'Phòng A1'),
       ('K002', N'Khoa Kinh tế', N'Phòng B2'),
       ('K003', N'Khoa Ngoại ngữ', N'Phòng C3');
INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINHD, PHAI, MAKHOA)
VALUES ('SV001', N'Nguyễn Văn A', '1999-05-10', N'Nam', 'K001'),
       ('SV002', N'Nguyễn Thị B', '2000-02-15', N'Nữ', 'K002'),
       ('SV003', N'Trần Văn C', '1998-09-20', N'Nam', 'K001');
INSERT INTO DIACHIDO (MADCD, TENDCD, NGAYDI)
VALUES ('D001', N'Địa chỉ đỏ A', '2023-06-01'),
       ('D002', N'Địa chỉ đỏ B', '2023-06-02'),
       ('D003', N'Địa chỉ đỏ C', '2023-06-03');
INSERT INTO DANGKY (MASV, MADCD, NGAYDK)
VALUES ('SV001', 'D001', '2023-06-01'),
       ('SV002', 'D001', '2023-06-02'),
       ('SV003', 'D002', '2023-06-03');





