CREATE DATABASE QL
GO
USE QL 
GO

-- Tạo bảng KHACHHANG
CREATE TABLE KHACHHANG (
    MAKH VARCHAR(10) PRIMARY KEY,
    TENKH NVARCHAR(50),
    TUOI INT,
    GIOITINH NVARCHAR(10),
    SODT VARCHAR(20)
);

-- Tạo bảng VACCINE
CREATE TABLE VACCINE (
    MAVACCINE VARCHAR(10) PRIMARY KEY,
    TENVACCINE NVARCHAR(50),
    NUOCSX NVARCHAR(50),
    HANSUDUNG DATE,
    TRANGTHAI NVARCHAR(20)
);

-- Tạo bảng PHIEUDAT
CREATE TABLE PHIEUDAT (
    MAPD VARCHAR(10) PRIMARY KEY,
    MAKH VARCHAR(10),
    NGAYDAT DATE,
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

-- Tạo bảng CHITIETPHIEUDAT
CREATE TABLE CHITIETPHIEUDAT (
    MAPD VARCHAR(10),
    MAVACCINE VARCHAR(10),
    SOLUONG INT,
    DONGIA DECIMAL(18,0),
    PRIMARY KEY (MAPD, MAVACCINE),
    FOREIGN KEY (MAPD) REFERENCES PHIEUDAT(MAPD),
    FOREIGN KEY (MAVACCINE) REFERENCES VACCINE(MAVACCINE)
);

-- Cấu trúc Constraint kiểm tra trạng thái Vaccine
ALTER TABLE VACCINE
ADD CONSTRAINT CK_VACCINE_TRANGTHAI CHECK (TRANGTHAI IN ('còn hàng', 'hết hàng'));

-- Cấu trúc Constraint kiểm tra giá trị duy nhất của TENVACCINE
ALTER TABLE VACCINE
ADD CONSTRAINT UQ_VACCINE_TENVACCINE UNIQUE (TENVACCINE);

-- Cấu trúc trigger kiểm tra ngày đặt là ngày hiện tại khi thêm phiếu đặt
CREATE TRIGGER TRG_PHIEUDAT_INSERT
ON PHIEUDAT
FOR INSERT
AS
BEGIN
    UPDATE PHIEUDAT
    SET NGAYDAT = GETDATE()
    WHERE MAPD IN (SELECT MAPD FROM inserted);
END;

-- Cấu trúc trigger kiểm tra số lượng lịch hẹn đăng ký tiêm Vaccine của mỗi khách hàng
CREATE TRIGGER TRG_PHIEUDAT_INSERT
ON PHIEUDAT
FOR INSERT
AS
BEGIN
    IF EXISTS (
        SELECT p.MAKH
        FROM PHIEUDAT p
        INNER JOIN inserted i ON p.MAPD = i.MAPD
        WHERE p.MAKH = i.MAKH
        GROUP BY p.MAKH
        HAVING COUNT(*) > 4 -- Số lượng lịch hẹn tối đa
    )
    BEGIN
        RAISERROR ('Mỗi khách hàng chỉ được đăng ký tối đa 4 lịch hẹn đăng ký tiêm Vaccine.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END;
END;

SELECT MAVACCINE, TENVACCINE, TRANGTHAI
FROM VACCINE
WHERE TENVACCINE = 'Phế cầu khuẩn' AND NUOCSX = 'Pháp';

SELECT KHACHHANG.MAKH, TENKH, SODT
FROM KHACHHANG
INNER JOIN PHIEUDAT ON KHACHHANG.MAKH = PHIEUDAT.MAKH
WHERE NGAYDAT = '2023-05-31';

SELECT MAKH, TENKH, TUOI, SODT
FROM KHACHHANG
WHERE MAKH NOT IN (SELECT MAKH FROM PHIEUDAT);

SELECT TOP 1 VACCINE.MAVACCINE, VACCINE.TENVACCINE
FROM VACCINE
INNER JOIN CHITIETPHIEUDAT ON VACCINE.MAVACCINE = CHITIETPHIEUDAT.MAVACCINE
GROUP BY VACCINE.MAVACCINE, VACCINE.TENVACCINE
ORDER BY COUNT(*) DESC

-- Dữ liệu cho bảng KHACHHANG
INSERT INTO KHACHHANG (MAKH, TENKH, TUOI, GIOITINH, SODT) VALUES ('KH001', N'Nguyễn Văn A', 25, N'Nam', '123456789');
INSERT INTO KHACHHANG (MAKH, TENKH, TUOI, GIOITINH, SODT) VALUES ('KH002', N'Nguyễn Thị B', 30, N'Nữ', '987654321');
INSERT INTO KHACHHANG (MAKH, TENKH, TUOI, GIOITINH, SODT) VALUES ('KH003', N'Trần Văn C', 40, N'Nam', '555555555');

-- Dữ liệu cho bảng VACCINE
INSERT INTO VACCINE (MAVACCINE, TENVACCINE, NUOCSX, HANSUDUNG, TRANGTHAI) VALUES ('VC001', N'Phế cầu khuẩn', N'Pháp', '2023-12-31', N'Còn hàng');
INSERT INTO VACCINE (MAVACCINE, TENVACCINE, NUOCSX, HANSUDUNG, TRANGTHAI) VALUES ('VC002', N'Vi rút corona', N'USA', '2023-11-30', N'Còn hàng');
INSERT INTO VACCINE (MAVACCINE, TENVACCINE, NUOCSX, HANSUDUNG, TRANGTHAI) VALUES ('VC003', N'Bạch hầu', N'Đức', '2023-10-31', N'Hết hàng');

-- Dữ liệu cho bảng PHIEUDAT
INSERT INTO PHIEUDAT (MAPD, MAKH, NGAYDAT) VALUES ('PD001', 'KH001', '2023-05-31');
INSERT INTO PHIEUDAT (MAPD, MAKH, NGAYDAT) VALUES ('PD002', 'KH002', '2023-05-31');
INSERT INTO PHIEUDAT (MAPD, MAKH, NGAYDAT) VALUES ('PD003', 'KH003', '2023-06-01');

-- Dữ liệu cho bảng CHITIETPHIEUDAT
INSERT INTO CHITIETPHIEUDAT (MAPD, MAVACCINE, SOLUONG, DONGIA) VALUES ('PD001', 'VC001', 3, 500000);
INSERT INTO CHITIETPHIEUDAT (MAPD, MAVACCINE, SOLUONG, DONGIA) VALUES ('PD002', 'VC002', 2, 400000);
INSERT INTO CHITIETPHIEUDAT (MAPD, MAVACCINE, SOLUONG, DONGIA) VALUES ('PD003', 'VC003', 1, 300000);