CREATE DATABASE Buoi1_QLTHUVIEN_Bai1 ON PRIMARY
(
    NAME = DB_PRIMARY,
    FILENAME = 'D:\VIsual Studio Code - Github\DBMS\THUCHANH\Buoi1\Bai1_QLTV\db_primary.mdf',
    SIZE = 3MB,
    MAXSIZE = 10MB,
    FILEGROWTH = 10%
),
(
    NAME = DB_SECOND1_1,
    FILENAME = 'D:\VIsual Studio Code - Github\DBMS\THUCHANH\Buoi1\Bai1_QLTV\DB_second1_1.ndf',
    SIZE = 3MB,
    MAXSIZE = 5MB,
    FILEGROWTH = 10%
),
(
    NAME = DB_SECOND1_2,
    FILENAME = 'D:\VIsual Studio Code - Github\DBMS\THUCHANH\Buoi1\Bai1_QLTV\DB_second1_2.ndf',
    SIZE = 3MB,
    MAXSIZE = 5MB,
    FILEGROWTH = 10%
),
(
    NAME = DB_SECOND1_3,
    FILENAME = 'D:\VIsual Studio Code - Github\DBMS\THUCHANH\Buoi1\Bai1_QLTV\DB_second1_3.ndf',
    SIZE = 3MB,
    MAXSIZE = 5MB,
    FILEGROWTH = 5%
)
LOG ON
(
    NAME = DB_Log,
    FILENAME = 'D:\VIsual Studio Code - Github\DBMS\THUCHANH\Buoi1\Bai1_QLTV\DB_Log.ldf',
    SIZE = 1MB,
    MAXSIZE = 5MB,
    FILEGROWTH = 15%
);
USE DB_QLTHUVIEN_Bai1

CREATE TABLE SACH
(
    MASH VARCHAR(10) PRIMARY KEY,
    TENSH NVARCHAR(50),
    TACGIA NVARCHAR(50),
    LOAI NVARCHAR(50),
    TINHTRANG NVARCHAR(50)
);

CREATE TABLE DOCGIA
(
    MADG VARCHAR(10) PRIMARY KEY,
    TENDG NVARCHAR(50),
    TUOI INT,
    PHAI NVARCHAR(3),
    DIACHI NVARCHAR(50)
);

CREATE TABLE MUONSACH
(
    MADG VARCHAR(10),
    MASH VARCHAR(10),
    NGAYMUON DATE,
    NGAYTRA DATE,
	CONSTRAINT FK_MUONSACH_DOCGIA FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG),
    CONSTRAINT FK_MUONSACH_SACH FOREIGN KEY (MASH) REFERENCES SACH(MASH)
);

SET DATEFORMAT DMY
--b) Thay đổi cấu trúc

ALTER TABLE DOCGIA
ALTER COLUMN PHAI NVARCHAR(5);

ALTER TABLE DOCGIA
ADD DIENTHOAI NVARCHAR(12),
    EMAIL NVARCHAR(50);

ALTER TABLE SACH
ADD NHAXUATBAN NVARCHAR(20);


